# Generated by Django 3.2.8 on 2022-12-21 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='photoo',
            new_name='photo',
        ),
    ]
