# Generated by Django 3.2.8 on 2022-12-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_photoo_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.FileField(default=2, upload_to='photos'),
            preserve_default=False,
        ),
    ]
